wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: validation_0-mlogloss
      6:
      - 3
      7:
      - 1
    python_version: 3.9.7
    start_time: 1721538967.493869
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 31
      4: 3.9.7
      5: 0.13.1
      8:
      - 1
      - 3
      - 5
    visualize:
      Feature Importance:
        panel_config:
          fieldSettings:
            label: Feature
            value: Importance
          panelDefId: wandb/bar/v0
          stringSettings:
            title: Feature Importance
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Feature Importance_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
learner:
  desc: null
  value:
    generic_param:
      fail_on_invalid_gpu_id: '0'
      gpu_id: '-1'
      n_jobs: '-1'
      nthread: '-1'
      random_state: '42'
      seed: '42'
      seed_per_iteration: '0'
      validate_parameters: '1'
    gradient_booster:
      gbtree_model_param:
        num_parallel_tree: '1'
        num_trees: '0'
        size_leaf_vector: '0'
      gbtree_train_param:
        predictor: auto
        process_type: default
        tree_method: hist
        updater: grow_quantile_histmaker
        updater_seq: grow_quantile_histmaker
      name: gbtree
      specified_updater: false
      updater:
        grow_quantile_histmaker:
          cpu_hist_train_param:
            single_precision_histogram: '0'
          train_param:
            alpha: '0'
            cache_opt: '1'
            colsample_bylevel: '1'
            colsample_bynode: '1'
            colsample_bytree: '1'
            eta: '0.100000001'
            gamma: '0'
            grow_policy: depthwise
            interaction_constraints: ''
            lambda: '1'
            learning_rate: '0.100000001'
            max_bin: '256'
            max_cat_to_onehot: '4'
            max_delta_step: '0'
            max_depth: '10'
            max_leaves: '0'
            min_child_weight: '1'
            min_split_loss: '0'
            monotone_constraints: ()
            refresh_leaf: '1'
            reg_alpha: '0'
            reg_lambda: '1'
            sampling_method: uniform
            sketch_eps: '0.0299999993'
            sketch_ratio: '2'
            sparse_threshold: '0.20000000000000001'
            subsample: '1'
    learner_model_param:
      base_score: 5E-1
      num_class: '7'
      num_feature: '9'
      num_target: '1'
    learner_train_param:
      booster: gbtree
      disable_default_eval_metric: '0'
      dsplit: auto
      objective: multi:softprob
    metrics: []
    objective:
      name: multi:softprob
      softmax_multiclass_param:
        num_class: '7'
version:
  desc: null
  value:
  - 1
  - 6
  - 1
